### PR TITLE
feat: Add support for jobs.

### PR DESCRIPTION
**Pull request by scstorytel**
Revisiting https://github.com/google-github-actions/deploy-cloudrun/pull/422 to add support for jobs.
These are the same set of changes.

Tests all pass for node 16, ran using `npm test`.

### CODE REVIEW

**Comment by dh-raufbhat** [comment]
Hello, just wanted to know if their are any plans to ship this. This seems to be a great feature and can support several use cases.

**Comment by nick-youngblut** [comment]
Any updates on this? It would be great to have support for Cloud Run jobs.

**Comment by banderson623** [comment]
This would be pretty great to add 👍

**Comment by braveenth** [comment]
+1 Added support for Jobs yaml here: https://github.com/braveenth/deploy-cloudrun/tree/add-cloud-run-job-yaml-support

**Comment by iennae** [comment]
@scstorytel could you resolve the currently conflicting files? I can take a look after that. Thanks.

**Comment by TigerC10** [comment]
@scstorytel we _do_ want to track `package-lock.json` because it pins the versions of 3rd party dependencies installed.  The `package.json` can specify version numbers in the form `^6.0.0` which would indicate "anything compatible with 6.0.0" rather than the specific 6.0.0 versioned release.  The package-lock will specify which exact version was installed.

**Pull request closed without merging**
